# Generated by Django 3.1 on 2020-10-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comuna',
        ),
    ]
