# Generated by Django 3.1 on 2020-10-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedor', '0002_delete_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comuna', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
