# Generated by Django 3.1 on 2020-10-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0003_comuna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comuna',
            new_name='comuna1',
        ),
    ]
