# Generated by Django 3.1 on 2020-10-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0004_auto_20201005_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='comuna1',
        ),
    ]
