# Generated by Django 3.1 on 2020-10-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0005_auto_20201005_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='region',
        ),
    ]
