# Generated by Django 3.1 on 2020-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0008_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.CharField(max_length=50)),
                ('imagen', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
