# Generated by Django 3.1 on 2020-10-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0010_marca_tipousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
    ]
